/* 
 * Generated by BootGen https://github.com/BootGen/BootGenVue
 */

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc; 
using WebProject.Services;

namespace WebProject.Controllers
{
    [ApiController]
    [Route("generate")]
    public class GenerateController : BaseController
    {
        private IGenerateService service;
        public GenerateController(IGenerateService service)
        {
            this.service = service;
        }

        [HttpPost]
        [Route("generate")]
        public IActionResult Generate([FromBody] GenerateRequest request)
        {
            var response = service.Generate(request);
            return new ObjectResult(response.ResponseData) { StatusCode = response.StatusCode };
        }
    }
}
