/* 
 * Generated by BootGen https://github.com/BootGen/BootGenVue
 */

using System;
using System.Text.Json.Serialization;
using System.Collections.Generic;
namespace WebProject
{
    public class AuthenticationData
    {
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
