openapi: '3.0.0'
info:
  version: 1.0.0
  title: 'BootGen Editor'
  license:
    name: MIT
servers:
  - url: https://api.bootgen.com
paths:
  /authentication/login:
    post:
      summary: login with email and password
      operationId: login
      responses:
        '200':
          description: successful login
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoginSuccess'
        '401':
          description: successful login
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoginError'
  /registration/register:
    post:
      summary: register with email and password
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/RegistrationData'
      responses:
        '200':
          description: response to registration request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProfileResponse'
  /registration/activate:
    post:
      summary: activate registration
      operationId: activate
      parameters:
        - name: activationCode
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful activation
        '400':
          description: activation error
  /profile:
    get:
      summary: get current user
      operationId: profile
      responses:
        '200':
          description: successful login
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: update profile
      operationId: updateProfile
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/User'
      responses:
        '200':
          description: response to update profile request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProfileResponse'
  /profile/change-password:
    post:
      summary: change password
      operationId: changePassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/ChangePasswordData'
      responses:
        '200':
          description: response to update profile request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChangePasswordResponse'
  /projects:
    get:
      summary: get list of projects
      security:
      - bearerAuth: []
      operationId: getProjects
      responses:
        '200':
          description: successful query
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
    post:
      summary: add a new element to the collection
      security:
      - bearerAuth: []
      operationId: addProject
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/Project'
      responses:
        '200':
          description: successful insertion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
  /projects/{projectId}:
    get:
      summary: get project
      security:
      - bearerAuth: []
      operationId: getProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
    put:
      summary: update project
      security:
      - bearerAuth: []
      operationId: updateProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/Project'
      responses:
        '200':
          description: successful update
    delete:
      summary: delete project
      security:
      - bearerAuth: []
      operationId: deleteProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful deletion
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 
  schemas:
    LoginSuccess:
      type: object
      required:
        - jwt
      properties:
        jwt:
          type: string
    LoginError:
      type: object
      required:
        - isInactive
        - wrongCreditentials
      properties:
        isInactive:
          type: boolean
        wrongCreditentials:
          type: boolean
    RegistrationData:
      type: object
      required:
        - userName
        - email
        - password
      properties:
        userName:
          type: string
        email:
          type: string
        password:
          type: string
    ProfileResponse:
      type: object
      required:
        - success
        - isUserNameInUse
        - isEmailInUse
      properties:
        success:
          type: boolean
        isUserNameInUse:
          type: boolean
        isEmailInUse:
          type: boolean
    User:
      type: object
      required:
        - id
        - userName
        - email
      properties:
        id:
          type: integer
          format: int32
          readOnly: true
        userName:
          type: string
        email:
          type: string
    ChangePasswordData:
      type: object
      required:
        - oldPassword
        - newPassword
      properties:
        oldPassword:
          type: string
        newPassword:
          type: string
    ChangePasswordResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
    Project:
      type: object
      required:
        - id
        - name
        - json
        - ownerId
      properties:
        id:
          type: integer
          format: int32
          readOnly: true
        name:
          type: string
        json:
          type: string
        ownerId:
          type: integer
          format: int32
