/* 
 * Generated by BootGen https://github.com/BootGen/BootGenVue
 */

using System;
using System.Text.Json.Serialization;
using System.Collections.Generic;
namespace WebProject
{
    public class ChangePasswordResponse
    {
        public bool Value { get; set; }
    }
}
