/* 
 * Generated by BootGen https://github.com/BootGen/BootGenVue
 */

using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;

namespace WebProject
{
    public class DataContext : DbContext
    {
        public DbSet<User> Users { get; set; }
        public DbSet<Project> Projects { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder options)
            => options.UseSqlite("Data Source=web_project.db");

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Project>()
                .HasOne(p => p.Owner)
                .WithMany()
                .HasForeignKey(p => p.OwnerId);

            modelBuilder.Entity<User>().HasData(new User {
                Id = 1,
                UserName = "Sample User",
                Email = "example@email.com",
                PasswordHash = "AQAAAAEAACcQAAAAEL//UdrNeiFjd0hYeQEBOtAN+OXME8tu8kNMTg4wZUrBSt1/t0Okfs389I82ZaIU2Q=="
            });
            modelBuilder.Entity<User>().HasData(new User {
                Id = 2,
                UserName = "Sample User 2",
                Email = "example2@email.com",
                PasswordHash = "AQAAAAEAACcQAAAAENZt+JlnUq5Ukt83M//z8Y/GlXWwYj6d260pmjQEz3Usac29eNfhmZTXHCGVOz70Hg=="
            });
            modelBuilder.Entity<User>().HasData(new User {
                Id = 3,
                UserName = "Sample User 3",
                Email = "example3@email.com",
                PasswordHash = "AQAAAAEAACcQAAAAENffyhoiBzkUXycLNzvQOYJJGCXsXw+7U2ZL1ED+kCFCnDmL4yGGQT7Xkr4ZaNV8/A=="
            });
            modelBuilder.Entity<Project>().HasData(new Project {
                Id = 1,
                Name = "First Project",
                Json = "{users: [{'userName': 'Test User', 'email': 'aa@bb@cc'}]}",
                OwnerId = 1
            });
        }
    }
}