/* 
 * Generated by BootGen https://github.com/BootGen/BootGenVue
 */

using System;
using System.Text.Json.Serialization;
using System.Collections.Generic;
namespace WebProject
{
    public class GenerateRequest
    {
        public string Data { get; set; }
        public bool GenerateClient { get; set; }
        public string NameSpace { get; set;}
    }
}
