// <auto-generated />
using System;
using Editor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Editor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210805082205_AddGitHubEventsTable")]
    partial class AddGitHubEventsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Editor.AppError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Info")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Kind")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("StackTrace")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("AppErrors");
                });

            modelBuilder.Entity("Editor.GitHubEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("GitHubEvents");
                });

            modelBuilder.Entity("Editor.OAuthUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Login")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("OAuthId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("OAuthUsers");
                });

            modelBuilder.Entity("Editor.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Backend")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Frontend")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Json")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Backend = "ASP.NET 5",
                            Frontend = "Vue 3 JavaScript",
                            Json = "{'users': [{'userName': 'Test User', 'email': 'aa@bb@cc'}]}",
                            Name = "First Project",
                            OwnerId = 1
                        });
                });

            modelBuilder.Entity("Editor.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Complexity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DataModel")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Diff")
                        .HasColumnType("int");

                    b.Property<int>("DownloadedCount")
                        .HasColumnType("int");

                    b.Property<string>("Example")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("GeneratedCount")
                        .HasColumnType("int");

                    b.Property<int>("Hash")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("Editor.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ActivationToken")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Newsletter")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "example@email.com",
                            IsActive = true,
                            Newsletter = true,
                            PasswordHash = "AQAAAAEAACcQAAAAEHxYcljd9Dco7pmsCBv6MWEnwCXYhvvm6qDS20/GHl6/5CiT7yoWzkWUvWcyoMBt/g==",
                            UserName = "Sample User"
                        },
                        new
                        {
                            Id = 2,
                            Email = "example2@email.com",
                            IsActive = true,
                            Newsletter = true,
                            PasswordHash = "AQAAAAEAACcQAAAAEIrOf1BRrFM4fsiVE2LMRChVt+JFJsKs+1NZQTu4EfO5xoz8nrAR7XnTfCcBO0MYVg==",
                            UserName = "Sample User 2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "example3@email.com",
                            IsActive = true,
                            Newsletter = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEHrP5hLtxJnq97Y8BMPB+Y0k86NQj5idSoy6R9F2RSfoNeiWNGLGpEkoFQlY0XM/Bg==",
                            UserName = "Sample User 3"
                        });
                });

            modelBuilder.Entity("Editor.OAuthUser", b =>
                {
                    b.HasOne("Editor.User", "User")
                        .WithOne()
                        .HasForeignKey("Editor.OAuthUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Editor.Project", b =>
                {
                    b.HasOne("Editor.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
