// <auto-generated />
using System;
using Editor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Editor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210709114425_ProjectFramework")]
    partial class ProjectFramework
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Editor.AppError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Info")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Kind")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("StackTrace")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("AppErrors");
                });

            modelBuilder.Entity("Editor.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Backend")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Frontend")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Json")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Backend = "ASP.NET 5",
                            Frontend = "Vue 3 JavaScript",
                            Json = "{'users': [{'userName': 'Test User', 'email': 'aa@bb@cc'}]}",
                            Name = "First Project",
                            OwnerId = 1
                        });
                });

            modelBuilder.Entity("Editor.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Complexity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DataModel")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Diff")
                        .HasColumnType("int");

                    b.Property<int>("DownloadedCount")
                        .HasColumnType("int");

                    b.Property<string>("Example")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("GeneratedCount")
                        .HasColumnType("int");

                    b.Property<int>("Hash")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("Editor.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ActivationToken")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Newsletter")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "example@email.com",
                            IsActive = true,
                            Newsletter = true,
                            PasswordHash = "AQAAAAEAACcQAAAAEMmWLw+HjbKYOAExlvptLGc2OeFHxQzwLK4KiHll6AGl+YDz3O2bVU+svowXWAsoMg==",
                            UserName = "Sample User"
                        },
                        new
                        {
                            Id = 2,
                            Email = "example2@email.com",
                            IsActive = true,
                            Newsletter = true,
                            PasswordHash = "AQAAAAEAACcQAAAAEFK2RdigN7cD3VOPrWuj2zIqAeXx6bsqbkKEo+GlHQzy3z/Xb4U7smUh0d1DmOoitw==",
                            UserName = "Sample User 2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "example3@email.com",
                            IsActive = true,
                            Newsletter = false,
                            PasswordHash = "AQAAAAEAACcQAAAAENrhCV1ChPdhpAWrLZ4tmFuL8kkfAUGi7D6FDi2vE68nkDNWECsLdCeSsRxxJwJn+A==",
                            UserName = "Sample User 3"
                        });
                });

            modelBuilder.Entity("Editor.Project", b =>
                {
                    b.HasOne("Editor.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
