/* 
 * Generated by BootGen https://github.com/BootGen/BootGenVue
 */

namespace WebProject.Services
{
    public interface IAuthenticationService
    {
        ServiceResponse<LoginResponse> Login(AuthenticationData data);
    }
}
