/* 
 * Generated by BootGen https://github.com/BootGen/BootGenVue
 */

namespace WebProject.Services
{
    public interface IProfileService
    {
        User CurrentUser { get; set; }
        ServiceResponse<User> Profile();
        ServiceResponse<ProfileResponse> UpdateProfile(User user);
        ServiceResponse<ChangePasswordResponse> ChangePassword(ChangePasswordData data);
    }
}
