/* 
 * Generated by BootGen https://github.com/BootGen/BootGenVue
 */

using System.Collections.Generic;
using System.Linq;
using BootGen;
using Newtonsoft.Json.Linq;
using WebProject.Generator;

namespace WebProject.Services
{
    public class GenerateService : IGenerateService
    {
        public ServiceResponse<GenerateResponse> Generate(GenerateRequest request)
        {
            try
            {
                DataModel dataModel = new DataModel();
                var collection = new JsonResourceCollection(dataModel);
                var jObject = JObject.Parse(request.Data);
                collection.Load(jObject);
                var generator = new Generator.Generator(collection, "Test");
                var files = generator.GenerateClasses().ToList();
                var seedStore = new JsonSeedStore(collection);
                seedStore.Load(jObject);
                var f = generator.GenerateDBContext(seedStore);
                files.Add(f);
                return new ServiceResponse<GenerateResponse> {
                    StatusCode = 200,
                    ResponseData = new GenerateResponse {
                        Success = true,
                        GeneratedFiles = files
                    }
                };
            } catch {
                return new ServiceResponse<GenerateResponse> {
                    StatusCode = 200,
                    ResponseData = new GenerateResponse {
                        Success = false,
                        ErrorMessage = "Unknown error",
                        GeneratedFiles = new List<GeneratedFile>()
                    }
                };
            }
        }
    }
}
