/* 
 * Generated by BootGen https://github.com/BootGen/BootGenVue
 */

namespace WebProject.Services
{
    public interface IGenerateService
    {
        ServiceResponse<GenerateResponse> Generate(GenerateRequest request);
    }
}
