/* 
 * Generated by BootGen https://github.com/BootGen/BootGenVue
 */

namespace WebProject.Services
{
    public interface IRegistrationService
    {
        ServiceResponse<ProfileResponse> Register(RegistrationData data);
    }
}
