<template>
  <v-container fluid>
    <v-row>
      <v-col cols="12" class="pl-0">
        <base-material-generator-card>
          <template v-slot:heading>
            <div class="d-flex display-1 font-weight-light align-center justify-space-between pa-2">
              <span class="text-break" v-if="activeFile && activeFile.name">{{ activeFile.name }}</span>
              <span v-else>Select a file</span>
              <div class="d-flex">
                <v-tooltip bottom>
                  <template v-slot:activator="{ on, attrs }">
                    <v-btn color="white" @click="drawer = !drawer" elevation="1" fab small v-bind="attrs" v-on="on">
                      <v-icon color="primary" v-if="drawer">mdi-folder-open</v-icon>
                      <v-icon color="primary" v-else>mdi-folder</v-icon>
                    </v-btn>
                  </template>
                  <span>Files</span>
                </v-tooltip>
                <settings-dialog></settings-dialog>
                <v-col class="d-flex fileSelector" v-if="drawer">
                  <v-treeview class="text-break" active-class="info--text" :items="tree" @update:active="selectFile" return-object activatable hoverable dense open-on-click></v-treeview>
                </v-col>
              </div>
            </div>
          </template>
          <codemirror v-if="activeFile && activeFile.content" v-model="activeFile.content" :options="cmOptions" />
          <codemirror v-else v-model="exampleFile" :options="cmOptions" />
        </base-material-generator-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script lang="ts">
import Vue from "vue";
import SettingsDialog from "../components/SettingsDialog.vue";

import { codemirror } from 'vue-codemirror'

import 'codemirror/lib/codemirror.css'
import "codemirror/mode/javascript/javascript.js";
import 'codemirror/theme/material.css'

interface File {
  name: string;
  path: string;
  content: string;
}

interface Element {
  id: number;
  name: string;
  content?: string;
  children: Element[];
}

export default Vue.extend({
  props:[
    "files"
  ],
  components: {
    SettingsDialog,
    codemirror
  },

  watch: {
    files: {
      handler(files: File[]) {
        if(this.activeFile){
          const name: string = this.activeFile.name;
          const result = files.find(file => file.name === name);
          if(result){
            this.activeFile.content = result.content;  
          }else{
            this.activeFile = null;
          }
        }
      }
    }
  },

  computed: {
    tree: function(): Element[]{
      let data: Element[] = [];
      let id = 0;
      for(const i in this.files){
        data = this.placement(data, this.files[i], id);
        id += 2;
      }
      return data;
    }
  },
  data: function () {
    return {
      activeFile: null as (null | Element),
      drawer: false,
      exampleFile: "/*Generated by BootGen https://github.com/BootGen/BootGenVue*/",
      cmOptions: {
        theme: 'material',
        tabSize: 2,
        mode: 'text/javascript',
        lineNumbers: true,
        line: true,
        readOnly: true,
      },
    };
  },
  methods: {
    selectFile: function(data: Element[]){
      if(data[0] && data[0].content){
        this.activeFile = data[0];
      }
    },
    placement: function(element: Element[], file: File, id: number): Element[]{
      let result = false;
      if(file.path === ""){
        element.push({id: id++, name: file.name, content: file.content, children: []});
      }else{
        for(const i in element){
          if(element[i].name === file.path){
            element[i].children.push({id: id++, name: file.name, content: file.content, children: []});
            result = true;
            break;
          }else if(element[i].children.length > 0){
            this.placement(element[i].children, file, id);
          }
        }
        if(!result){
          element.push({id: id++, name: file.path, children: [{id: id++, name: file.name, content: file.content, children: []}]});
        }
      }
      return element;
    }
  },
});
</script>

<style lang="css">
  .fileSelector {
    position: absolute;
    background:#412fb3;
    top: 55px;
    right: 0px;
    width: fit-content;
    border-radius: 3px;
    word-wrap: break-word!important;
  }
</style>