<template>
  <v-container fluid>
    <v-row>
      <v-col cols="8">
        <highlightjs v-if="activeFile && activeFile.content" language='csharp' :code="activeFile.content" />
        <highlightjs v-else language='csharp' code="/* Generated by BootGen https://github.com/BootGen/BootGenVue */" />
      </v-col>
      <v-col cols="4">
        <v-treeview :items="tree" @update:active="selectFile" return-object activatable hoverable dense open-on-click></v-treeview>
      </v-col>
    </v-row>
  </v-container>
</template>

<script lang="ts">
import Vue from "vue";

interface File {
  name: string;
  path: string;
  content: string;
}

interface Element {
  id: number;
  name: string;
  content?: string;
  children: Element[];
}

export default Vue.extend({
  props:[
    "files"
  ],
  components: {
  },

  watch: {
    files: {
      handler(files: File[]) {
        if(this.activeFile){
          const name: string = this.activeFile.name;
          const result = files.find(file => file.name === name);
          if(result){
            this.activeFile.content = result.content;  
          }else{
            this.activeFile = null;
          }
        }
      }
    }
  },

  computed: {
    tree: function(): Element[]{
      let data: Element[] = [];
      let id = 0;
      for(const i in this.files){
        data = this.placement(data, this.files[i], id);
        id += 2;
      }
      return data;
    }
  },
  data: function () {
    return {
      activeFile: null as (null | Element),
    };
  },
  methods: {
    selectFile: function(data: Element[]){
      if(data[0] && data[0].content){
        this.activeFile = data[0];
      }
    },
    placement: function(element: Element[], file: File, id: number): Element[]{
      let result = false;
      if(file.path === ""){
        element.push({id: id++, name: file.name, content: file.content, children: []});
      }else{
        for(const i in element){
          if(element[i].name === file.path){
            element[i].children.push({id: id++, name: file.name, content: file.content, children: []});
            result = true;
            break;
          }else if(element[i].children.length > 0){
            this.placement(element[i].children, file, id);
          }
        }
        if(!result){
          element.push({id: id++, name: file.path, children: [{id: id++, name: file.name, content: file.content, children: []}]});
        }
      }
      return element;
    }
  },
});
</script>

<style lang="css">
  .v-application code{
    color: rgb(0,0,0);
    background-color: #e8e8e8;
    padding: 15px;
  }
</style>