name: Test

on:
  push:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        lfs: true
    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - name: Checkout LFS objects
      run: git lfs pull
    - name: Install dependencies (nuget)
      run: dotnet restore
    - name: Build Server
      run: dotnet build
    - name: Configure Server
      run: cp appsettings.Development.json appsettings.json
      working-directory: ./bin/Debug/net5.0
    - name: Build DB
      run: dotnet tool uninstall --global dotnet-ef
      run: chmod +x resetdb.sh ; ./resetdb.sh ; cp editor.db bin/Debug/net5.0/editor.db
    - name: Install dependencies (npm)
      run: npm ci
      working-directory: ./ClientApp
    - name: Test
      run: chmod +x run.sh ; bash run.sh & npm run test:e2e
      working-directory: ./ClientApp
